In [1]:
import pandas as pd
import numpy as np
from math import *
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse

In [2]:
example_rating = np.array([[2,np.nan,np.nan,5,1,np.nan],[np.nan,np.nan,3,4,3,1],[3,1,3,np.nan,5,np.nan],
                           [np.nan,4,np.nan,np.nan,5,3],[np.nan,1,2,3,np.nan,np.nan],[1,np.nan,2,np.nan,2,np.nan]])
example_rating

array([[ 2., nan, nan,  5.,  1., nan],
       [nan, nan,  3.,  4.,  3.,  1.],
       [ 3.,  1.,  3., nan,  5., nan],
       [nan,  4., nan, nan,  5.,  3.],
       [nan,  1.,  2.,  3., nan, nan],
       [ 1., nan,  2., nan,  2., nan]])

In [3]:
selected_users = example_rating[1:3]
selected_users

array([[nan, nan,  3.,  4.,  3.,  1.],
       [ 3.,  1.,  3., nan,  5., nan]])

In [4]:
euclidean_distance_matrix = []
for i in selected_users:
    user_distance = []
    for j in example_rating:
        print("User 1:",i)
        print("User 2:",j)
        vector_distance = i - j
        print("vector_distance: ", vector_distance)
        euclidean_calc = 0
        for ele in vector_distance:
            if isnan(ele) == False:
                euclidean_calc += ele*ele
        user_distance.append(sqrt(euclidean_calc))
        print(sqrt(euclidean_calc))
    euclidean_distance_matrix.append(user_distance)

User 1: [nan nan  3.  4.  3.  1.]
User 2: [ 2. nan nan  5.  1. nan]
vector_distance:  [nan nan nan -1.  2. nan]
2.23606797749979
User 1: [nan nan  3.  4.  3.  1.]
User 2: [nan nan  3.  4.  3.  1.]
vector_distance:  [nan nan  0.  0.  0.  0.]
0.0
User 1: [nan nan  3.  4.  3.  1.]
User 2: [ 3.  1.  3. nan  5. nan]
vector_distance:  [nan nan  0. nan -2. nan]
2.0
User 1: [nan nan  3.  4.  3.  1.]
User 2: [nan  4. nan nan  5.  3.]
vector_distance:  [nan nan nan nan -2. -2.]
2.8284271247461903
User 1: [nan nan  3.  4.  3.  1.]
User 2: [nan  1.  2.  3. nan nan]
vector_distance:  [nan nan  1.  1. nan nan]
1.4142135623730951
User 1: [nan nan  3.  4.  3.  1.]
User 2: [ 1. nan  2. nan  2. nan]
vector_distance:  [nan nan  1. nan  1. nan]
1.4142135623730951
User 1: [ 3.  1.  3. nan  5. nan]
User 2: [ 2. nan nan  5.  1. nan]
vector_distance:  [ 1. nan nan nan  4. nan]
4.123105625617661
User 1: [ 3.  1.  3. nan  5. nan]
User 2: [nan nan  3.  4.  3.  1.]
vector_distance:  [nan nan  0. nan  2. nan]
2.0


In [5]:
euclidean_distance_matrix = np.array(euclidean_distance_matrix).T
euclidean_distance_matrix

array([[2.23606798, 4.12310563],
       [0.        , 2.        ],
       [2.        , 0.        ],
       [2.82842712, 3.        ],
       [1.41421356, 1.        ],
       [1.41421356, 3.74165739]])

In [6]:
A_sparse = sparse.csr_matrix(euclidean_distance_matrix)
cosine_similarities = cosine_similarity(A_sparse)
cosine_similarities.round(2)

array([[1.  , 0.88, 0.48, 0.97, 0.9 , 0.99],
       [0.88, 1.  , 0.  , 0.73, 0.58, 0.94],
       [0.48, 0.  , 1.  , 0.69, 0.82, 0.35],
       [0.97, 0.73, 0.69, 1.  , 0.98, 0.92],
       [0.9 , 0.58, 0.82, 0.98, 1.  , 0.83],
       [0.99, 0.94, 0.35, 0.92, 0.83, 1.  ]])

In [7]:
def calc_cosine_similarity(arr):
    
    # Caclculate euclidean distance between users, perform parallelization here
    euclidean_distance_matrix = []
    for i in arr:
        user_distance = []
        for j in arr:
            vector_distance = i - j
            euclidean_calc = 0
            for ele in vector_distance:
                if isnan(ele) == False:
                    euclidean_calc += ele*ele
            user_distance.append(sqrt(euclidean_calc))
        euclidean_distance_matrix.append(user_distance)

    # Calculate cosine similarity
    euclidean_distance_matrix = np.array(euclidean_distance_matrix).T
    A_sparse = sparse.csr_matrix(euclidean_distance_matrix)
    cosine_similarities = cosine_similarity(A_sparse)

    return cosine_similarities

In [8]:
calc_cosine_similarity(example_rating)

array([[1.        , 0.80231771, 0.53404806, 0.61085027, 0.72684523,
        0.88749217],
       [0.80231771, 1.        , 0.79407499, 0.71592788, 0.81599401,
        0.80342118],
       [0.53404806, 0.79407499, 1.        , 0.75928127, 0.7481376 ,
        0.50662578],
       [0.61085027, 0.71592788, 0.75928127, 1.        , 0.52510503,
        0.56273187],
       [0.72684523, 0.81599401, 0.7481376 , 0.52510503, 1.        ,
        0.84534109],
       [0.88749217, 0.80342118, 0.50662578, 0.56273187, 0.84534109,
        1.        ]])

In [9]:
movie_id = "imdb_id"
author_username = "author"
ratings = "stars"

In [10]:
train_df = pd.read_csv("training_set.csv")
test_df = pd.read_csv("testing_set.csv")

In [12]:
df_matrix = train_df.pivot_table(index=author_username, columns=movie_id, values=ratings)
df_matrix.reset_index(inplace=True)

In [14]:
df_matrix = df_matrix[:100]
df_matrix

imdb_id         author  tt0000417  tt0010323  tt0013442  tt0015648  tt0015864  \
0           007Waffles        NaN        NaN        NaN        NaN        NaN   
1             00Yasser        NaN        NaN        NaN        NaN        NaN   
2         04GreatFlick        NaN        NaN        NaN        NaN        NaN   
3               0maro0        NaN        NaN        NaN        NaN        NaN   
4                  0w0        NaN        NaN        NaN        NaN        NaN   
..                 ...        ...        ...        ...        ...        ...   
95       AirBourne_Bds        NaN        NaN        NaN        NaN        NaN   
96            Airman87        NaN        NaN        NaN        NaN        NaN   
97           Ajtlawyer        NaN        NaN        NaN        NaN        NaN   
98         Akash_Menon        NaN        NaN        NaN        NaN        NaN   
99            Akira-36        NaN        NaN        NaN        NaN        NaN   

imdb_id  tt0017136  tt0020629  tt0021749  tt0021814  ...  tt9784708  \
0              NaN        NaN        NaN        NaN  ...        NaN   
1              NaN        NaN        NaN        NaN  ...        NaN   
2              NaN        NaN        NaN        NaN  ...        NaN   
3              NaN        NaN        NaN        NaN  ...        NaN   
4              NaN        NaN        NaN        NaN  ...        NaN   
..             ...        ...        ...        ...  ...        ...   
95             NaN        NaN        NaN        NaN  ...        NaN   
96             NaN        NaN        NaN        NaN  ...        NaN   
97             NaN        NaN        NaN        NaN  ...        NaN   
98             NaN        NaN        NaN        NaN  ...        NaN   
99             NaN        NaN        NaN        NaN  ...        NaN   

imdb_id  tt9784798  tt9794630  tt9806370  tt9831136  tt9844522  tt9845564  \
0              NaN        NaN        NaN        NaN        NaN        NaN   
1              NaN        NaN        NaN        NaN        NaN        NaN   
2              NaN        NaN        NaN        NaN        NaN        NaN   
3              NaN        NaN        NaN        NaN        NaN        NaN   
4              NaN        NaN        NaN        NaN        NaN        NaN   
..             ...        ...        ...        ...        ...        ...   
95             NaN        NaN        NaN        NaN        NaN        NaN   
96             NaN        NaN        NaN        NaN        NaN        NaN   
97             NaN        NaN        NaN        NaN        NaN        NaN   
98             NaN        NaN        NaN        NaN        NaN        NaN   
99             NaN        NaN        NaN        NaN        NaN        NaN   

imdb_id  tt9848626  tt9866072  tt9907782  
0              NaN        NaN        NaN  
1              NaN        NaN        NaN  
2              NaN        NaN        NaN  
3              NaN        NaN        NaN  
4              NaN        NaN        NaN  
..             ...        ...        ...  
95             NaN        NaN        NaN  
96             NaN        NaN        NaN  
97             NaN        NaN        NaN  
98             NaN        NaN        NaN  
99             NaN        NaN        NaN  

[100 rows x 4231 columns]

In [15]:
df_matrix.isnull().sum(axis=1)

0     4192
1     4218
2     4218
3     4220
4     4139
      ... 
95    4209
96    4216
97    4207
98    4216
99    4214
Length: 100, dtype: int64