In [25]:
import pandas as pd
import numpy as np
from math import *
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse

In [2]:
example_rating = np.array([[2,np.nan,np.nan,5,1,np.nan],[np.nan,np.nan,3,4,3,1],[3,1,3,np.nan,5,np.nan],
                           [np.nan,4,np.nan,np.nan,5,3],[np.nan,1,2,3,np.nan,np.nan],[1,np.nan,2,np.nan,2,np.nan]])
example_rating

array([[ 2., nan, nan,  5.,  1., nan],
       [nan, nan,  3.,  4.,  3.,  1.],
       [ 3.,  1.,  3., nan,  5., nan],
       [nan,  4., nan, nan,  5.,  3.],
       [nan,  1.,  2.,  3., nan, nan],
       [ 1., nan,  2., nan,  2., nan]])

In [3]:
selected_users = example_rating[1:3]
selected_users

array([[nan, nan,  3.,  4.,  3.,  1.],
       [ 3.,  1.,  3., nan,  5., nan]])

In [36]:
euclidean_distance_matrix = []
for i in selected_users:
    user_distance = []
    for j in example_rating:
        print("User 1:",i)
        print("User 2:",j)
        vector_distance = i - j
        euclidean_calc = 0
        for ele in vector_distance:
            if isnan(ele) == False:
                euclidean_calc += ele*ele
        user_distance.append(sqrt(euclidean_calc))
        print(sqrt(euclidean_calc))
    euclidean_distance_matrix.append(user_distance)

User 1: [nan nan  3.  4.  3.  1.]
User 2: [ 2. nan nan  5.  1. nan]
2.23606797749979
User 1: [nan nan  3.  4.  3.  1.]
User 2: [nan nan  3.  4.  3.  1.]
0.0
User 1: [nan nan  3.  4.  3.  1.]
User 2: [ 3.  1.  3. nan  5. nan]
2.0
User 1: [nan nan  3.  4.  3.  1.]
User 2: [nan  4. nan nan  5.  3.]
2.8284271247461903
User 1: [nan nan  3.  4.  3.  1.]
User 2: [nan  1.  2.  3. nan nan]
1.4142135623730951
User 1: [nan nan  3.  4.  3.  1.]
User 2: [ 1. nan  2. nan  2. nan]
1.4142135623730951
User 1: [ 3.  1.  3. nan  5. nan]
User 2: [ 2. nan nan  5.  1. nan]
4.123105625617661
User 1: [ 3.  1.  3. nan  5. nan]
User 2: [nan nan  3.  4.  3.  1.]
2.0
User 1: [ 3.  1.  3. nan  5. nan]
User 2: [ 3.  1.  3. nan  5. nan]
0.0
User 1: [ 3.  1.  3. nan  5. nan]
User 2: [nan  4. nan nan  5.  3.]
3.0
User 1: [ 3.  1.  3. nan  5. nan]
User 2: [nan  1.  2.  3. nan nan]
1.0
User 1: [ 3.  1.  3. nan  5. nan]
User 2: [ 1. nan  2. nan  2. nan]
3.7416573867739413


In [37]:
euclidean_distance_matrix = np.array(euclidean_distance_matrix).T
euclidean_distance_matrix

array([[2.23606798, 4.12310563],
       [0.        , 2.        ],
       [2.        , 0.        ],
       [2.82842712, 3.        ],
       [1.41421356, 1.        ],
       [1.41421356, 3.74165739]])

In [38]:
A_sparse = sparse.csr_matrix(euclidean_distance_matrix)
cosine_similarities = cosine_similarity(A_sparse)
cosine_similarities.round(2)

array([[1.  , 0.88, 0.48, 0.97, 0.9 , 0.99],
       [0.88, 1.  , 0.  , 0.73, 0.58, 0.94],
       [0.48, 0.  , 1.  , 0.69, 0.82, 0.35],
       [0.97, 0.73, 0.69, 1.  , 0.98, 0.92],
       [0.9 , 0.58, 0.82, 0.98, 1.  , 0.83],
       [0.99, 0.94, 0.35, 0.92, 0.83, 1.  ]])

In [ ]:
def calc_cosine_similarity(arr):
    
    # Caclculate euclidean distance between users, perform parallelization here
    euclidean_distance_matrix = []
    for i in arr:
        user_distance = []
        for j in arr:
            vector_distance = i - j
            euclidean_calc = 0
            for ele in vector_distance:
                if isnan(ele) == False:
                    euclidean_calc += ele*ele
            user_distance.append(sqrt(euclidean_calc))
        euclidean_distance_matrix.append(user_distance)

    # Calculate cosine similarity
    euclidean_distance_matrix = np.array(euclidean_distance_matrix).T
    A_sparse = sparse.csr_matrix(euclidean_distance_matrix)
    cosine_similarities = cosine_similarity(A_sparse)

    return cosine_similarities